(define (domain minecraft)
  (:requirements :strips :existential-preconditions)
  
  (:predicates
    (at-robot ?pos)           
    (block-at ?b ?pos)        
    (holding ?b)             
    (handempty)               
    (free ?pos)               
    (adjacent ?pos1 ?pos2)    
    (above ?pos1 ?pos2)       
    (ground-pos ?pos)         
    (on-ground ?b)            
    (block-above ?b1 ?b2)     
    (clear ?b)                
  )
  
  (:action move
    :parameters (?from ?to)
    :precondition (and (at-robot ?from)
                     (adjacent ?from ?to)
                     (free ?to))
    :effect (and (not (at-robot ?from))
                 (at-robot ?to)
                 (free ?from)
                 (not (free ?to)))
  )
  
  (:action pickup
    :parameters (?b ?bpos ?rpos)
    :precondition (and (block-at ?b ?bpos)
                     (at-robot ?rpos)
                     (adjacent ?rpos ?bpos)
                     (handempty)
                     (clear ?b))
    :effect (and (not (block-at ?b ?bpos))
                 (not (handempty))
                 (holding ?b)
                 (free ?bpos)
                 (not (clear ?b))
                 
                 ; Handle block relationships
                 (forall (?b2)
                   (when (block-above ?b ?b2)
                     (and (clear ?b2)
                          (not (block-above ?b ?b2)))))
                 
                 (when (on-ground ?b)
                   (not (on-ground ?b)))
    )
  )
  
  (:action putdown-on-ground
    :parameters (?b ?bpos ?rpos)
    :precondition (and (holding ?b)
                      (at-robot ?rpos)
                      (adjacent ?rpos ?bpos)
                      (free ?bpos)
                      (ground-pos ?bpos))
    :effect (and (not (holding ?b))
                 (handempty)
                 (block-at ?b ?bpos)
                 (not (free ?bpos))
                 (clear ?b)
                 (on-ground ?b))
  )
  
  (:action putdown-on-block
    :parameters (?b ?bpos ?rpos ?b2 ?b2pos)
    :precondition (and (holding ?b)
                      (at-robot ?rpos)
                      (adjacent ?rpos ?bpos)
                      (free ?bpos)
                      (block-at ?b2 ?b2pos)
                      (above ?bpos ?b2pos)
                      (clear ?b2))
    :effect (and (not (holding ?b))
                 (handempty)
                 (block-at ?b ?bpos)
                 (not (free ?bpos))
                 (clear ?b)
                 (not (clear ?b2))
                 (block-above ?b ?b2))
  )
)